garrett528/support aws msk sasl
UrbanCompass/librdkafka pull request #1
Opened 2021-07-20 18:44 UTC by garrett528

- Add NetBeans project files to gitignore
- Update configuration to provide SASL_AWS_MSK_IAM option
- Added property for AWS-MSK-IAM SASL authentication
- Generate payload implementation
- Implements server response handling
- Updated to use rd_snprintf where possible
- Added AWS creds to conf
- Add openssl_engine_example_cpp executable to gitignore
- Initial working client

2021-07-26 22:25 UTC, praveen-solanki-compass requested changes
This is awesome work ! Some minor comments.

2021-07-26 22:25 UTC, praveen-solanki-compass commented on src/rdstringbuilder.c
> +    sb->str = realloc(sb->str, sb->alloced);
Good to check if realloc returned NULL, in that case log something and call exit(1) if appropriate or bubble up.

2021-07-26 22:25 UTC, praveen-solanki-compass commented on src/rdstringbuilder.c
> +/*
Add some unit tests for the utilities in here.

2021-07-26 22:25 UTC, praveen-solanki-compass commented on src/rdstringbuilder.c
> +void str_builder_add_int(str_builder_t *sb, int val)
use `unsigned int` if possible

2021-07-26 22:25 UTC, praveen-solanki-compass commented on src/rdstringbuilder.c
> +    str_builder_truncate(sb, 0);
This is sufficient
```
sb->len = 0;
sb->str[0] = '\0';

```

2021-07-26 22:25 UTC, praveen-solanki-compass commented on src/rdstringbuilder.c
> +void str_builder_drop(str_builder_t *sb, size_t len)
This method is quite confusing. Why you need this?

2021-07-26 22:25 UTC, praveen-solanki-compass commented on src/rdstringbuilder.c
> +const char *str_builder_peek(const str_builder_t *sb)
Caller can just do sb->str ?

2021-07-26 22:25 UTC, praveen-solanki-compass commented on src/rdstringbuilder.c
> +size_t str_builder_len(const str_builder_t *sb)
Caller can just do sb->len

2021-07-26 22:25 UTC, praveen-solanki-compass commented on src/rdstringbuilder.c
> +char *str_builder_dump(const str_builder_t *sb, size_t *len)
Sugges to create a small struct, may be something like 
```
{
    char * buf;
    unsigned int size;
}
```
and fill that up and return?
Using pointer to capture size and return value for out seems unclean

2021-07-26 22:28 UTC, praveen-solanki-compass commented on src/rdkafka_sasl_aws_msk_iam.c
> +        str_builder_add_str(sb, "GET\n", 0);
How about dropping the last param to str_builder_add_str, you seem to always pass in 0

2021-07-26 22:39 UTC, praveen-solanki-compass commented on src/rdkafka_sasl_aws_msk_iam.c
> +        const char aws_req[27] = "kafka-cluster/aws4_request";
You can also do a `const char * aws_req = "kafka-cluster/aws4_request";
Const strings are allocatated in data segement.

2021-07-26 22:39 UTC, praveen-solanki-compass commented on src/rdkafka_sasl_aws_msk_iam.c
> +        sb = str_builder_create();
Why not just create a simple struct variable in this local stack instead of doing *sb = calloc(1, sizeof(struct..)).
Only use dynamic allocation where needed. Creating stuff in stack is much faster.

2021-07-27 00:00 UTC, garrett528 commented
@praveen-solanki-compass i basically copied most of the stringbuilder impl from https://nachtimwald.com/2017/02/26/efficient-c-string-builder/. i'll go through your comments and add some checks but that's why things related to that file / object are the way they are.

2021-07-27 12:56 UTC, garrett528 commented on src/rdkafka_sasl_aws_msk_iam.c
> +        sb = str_builder_create();
i think it's doing this to preserve the dynamic nature of building a string. i'm not worried about performance here since these calls are made very infrequently (only a couple of times during initial startup and never again unless the channel needs to be reopened).

2021-07-27 13:02 UTC, garrett528 commented on src/rdstringbuilder.c
> +void str_builder_drop(str_builder_t *sb, size_t len)
that's a utility if you were to be reusing an instance of string builder and allows you to reuse the same string builder to build multiple different strings without creating and destroying the sb instance each time.

2021-07-27 13:03 UTC, garrett528 commented on src/rdstringbuilder.c
> +    str_builder_truncate(sb, 0);
what's the downside to leaving the truncate call?

2021-07-27 13:04 UTC, garrett528 commented on src/rdstringbuilder.c
> +void str_builder_add_int(str_builder_t *sb, int val)
what if you need to add a negative number to the string? again, this is basically copying that implementation so we likely don't need this method anyways but is there anything wrong with the fundamental implementation here?

2021-07-27 13:14 UTC, garrett528 commented on src/rdstringbuilder.c
> +const char *str_builder_peek(const str_builder_t *sb)
looks like that has NULL guard. according to the header file "data is guaranteed to be NULL terminated"

2021-07-27 13:15 UTC, garrett528 commented on src/rdstringbuilder.c
> +size_t str_builder_len(const str_builder_t *sb)
looks like it has a NULL guard in the impl. probably not 100% necessary but don't think it's hurting anything either

2021-07-27 13:17 UTC, garrett528 commented on src/rdkafka_sasl_aws_msk_iam.c
> +        str_builder_add_str(sb, "GET\n", 0);
this is most likely here to mimic snprintf functionality and provide security against write more bytes than your buffer has space for

2021-07-27 13:44 UTC, garrett528 commented on src/rdstringbuilder.c
> +char *str_builder_dump(const str_builder_t *sb, size_t *len)
maybe i'm not understanding something here but what's the issue? we're just returning the char pointer. later in the code i may convert this to an rd_chariov_t which is basically the struct you suggested. for this particular method, why is returning the size important when we can strlen the char * when/ if we need it?

2021-07-27 13:47 UTC, garrett528 commented on src/rdstringbuilder.c
> +    sb->str = realloc(sb->str, sb->alloced);
done

2021-07-27 13:47 UTC, garrett528 commented on src/rdkafka_sasl_aws_msk_iam.c
> +        const char aws_req[27] = "kafka-cluster/aws4_request";
done

2021-07-27 14:04 UTC, praveen-solanki-compass commented on src/rdstringbuilder.c
> +void str_builder_add_int(str_builder_t *sb, int val)
yeah, if we are not using let remove those. Cleaner in my opinion.

2021-07-27 14:08 UTC, praveen-solanki-compass commented on src/rdstringbuilder.c
> +char *str_builder_dump(const str_builder_t *sb, size_t *len)
Its not readable and seems hackish. This function produces output both as return value and as a change to parameter reference.

2021-07-27 14:40 UTC, garrett528 commented on src/rdstringbuilder.c
> +char *str_builder_dump(const str_builder_t *sb, size_t *len)
changed this to not have an option to set that. in this project, we use rd_chariov_t if we want to pass a char pointer and size struct. i'd rather just have this return the char pointer and we can convert this to that struct for passing if needed.

2021-07-27 14:41 UTC, garrett528 commented on src/rdstringbuilder.c
> +size_t str_builder_len(const str_builder_t *sb)
using for unittests

2021-07-27 14:42 UTC, garrett528 commented on src/rdstringbuilder.c
> +const char *str_builder_peek(const str_builder_t *sb)
using for unit tests

2021-07-27 14:42 UTC, garrett528 commented on src/rdstringbuilder.c
> +void str_builder_add_int(str_builder_t *sb, int val)
removed

2021-07-27 14:42 UTC, garrett528 commented on src/rdstringbuilder.c
> +/*
added

2021-07-27 14:43 UTC, garrett528 commented on src/rdstringbuilder.c
> +    str_builder_truncate(sb, 0);
truncate and drop are useful calls. it's nice to only need to remember to make a call rather than those two operations. while it may add a single additional call to the call stack, it's more readable and simpler to deal with from an API perspective.

2021-07-27 14:46 UTC, garrett528 commented on examples/producer.c
> +        if (argc == 3) {
C counts the first part of a CLI command as the first arg in ARGV[0]. so something like `./producer arg1 arg2`, "./producer" is considered the first argument in ARGV[0]. that's why everything is incremented by 1.

2021-07-27 17:12 UTC, pablomata approved these changes

2021-07-27 17:12 UTC, pablomata commented on src/rdkafka_sasl_aws_msk_iam.c
> +//        printf("Signature:\n%s\n", res_hexstring);
nit: I suppose you don't need this anymore :)

2021-07-27 17:27 UTC, praveen-solanki-compass approved these changes
LGTM. Thanks !!

2021-07-27 17:48 UTC, merged